### ISSUE TITLE
How do I setup this project?

### ISSUE THREAD

**Issue by sabbiu** [LukeWlodarczyk/Slack-Clone-Server#1]
I am new to docker. How do I run this project?

This is the error I get at the time of build
```
Removing intermediate container 6f5cdb9f1f14
 ---> f631a4c0c26a
Step 6/8 : COPY dist .
COPY failed: stat /var/lib/docker/tmp/docker-builder128141946/dist: no such file or directory
```

**Comment by LukeWlodarczyk** [comment]
Hey,
Did you solve your problem? 
As far as I can see, there is no 'dist' folder. Make sure to run 
`npm build`
Create a 'files' directory in root folder as well.
I hope it will help you.

I will add some more instructions how to setup this project this week.

**Comment by sabbiu** [comment]
Yes, I was able to run it successfully. Thanks
